# This YAML file is used to display the IP ddress using facts options

---
- name: SHOW IP ADDRESS
  hosts: all
  tasks:
    - name: Show IP address
      debug: 
        msg: >
          This host use IP address {{ansible_facts.default_ipv4.address}}
