---

- name: Net-tools mudole
  hosts: all       
  become: yes                     
  
  tasks:
    - name: Test set facts
      set_fact:
        defined_set_fact: "set facts by admin"
    - debug: 
        var: defined_set_fact


