# Define a group_var to place the variables
# Define a host_var to place the host list
# Define a main.yaml file

- name: Hello World
  hosts: all

  tasks:
    - name: Test vars
      debug: 
        msg: "ansible_user= {{ ansible_user }}, ansible_password= {{ ansible_password }}, http_port= {{ http_port }}"