# 1.3 loop - dispaly all the item using a nested loop

- name: Hello World
  hosts: localhost

  vars:
    looptest1:
      - test1
      - test2
      - test3
      - test4

    looptest2:
      - demo1
      - demo2
      - demo3

  tasks:
    - name: Test loop
      debug: 
        msg: "{{item[0]}}, {{item[1]}}"
      with_nested:
        - "{{looptest1}}"
        - "{{looptest2}}"

# Result: 

# TASK [Test loop] ********************************************************************************************************************************************************************************************************
# ok: [localhost] => (item=['test1', 'demo1']) => {
#     "msg": "test1, demo1"
# }
# ok: [localhost] => (item=['test1', 'demo2']) => {
#     "msg": "test1, demo2"
# }
# ok: [localhost] => (item=['test1', 'demo3']) => {
#     "msg": "test1, demo3"
# }
# ok: [localhost] => (item=['test2', 'demo1']) => {
#     "msg": "test2, demo1"
# }
# ok: [localhost] => (item=['test2', 'demo2']) => {
#     "msg": "test2, demo2"
# }
# ok: [localhost] => (item=['test2', 'demo3']) => {
#     "msg": "test2, demo3"
# }
# ok: [localhost] => (item=['test3', 'demo1']) => {
#     "msg": "test3, demo1"
# }
# ok: [localhost] => (item=['test3', 'demo2']) => {
#     "msg": "test3, demo2"
# }
# ok: [localhost] => (item=['test3', 'demo3']) => {
#     "msg": "test3, demo3"
# }
# ok: [localhost] => (item=['test4', 'demo1']) => {
#     "msg": "test4, demo1"
# }
# ok: [localhost] => (item=['test4', 'demo2']) => {
#     "msg": "test4, demo2"
# }
# ok: [localhost] => (item=['test4', 'demo3']) => {
#     "msg": "test4, demo3"
# }
