# Python.yml file used to install the requirements for pip

---

- name: Install Python 3
  hosts: all       
  gather_facts: no                     
  
  tasks:
    - name: Install python on CentOS
      become: yes
      yum:
        name: 
          - python3
          - python3-devel
          - python3-pip
          - python-setuptools
        state: present
        