# Ver.2 of the project using the roles. 
# Create two different roles - one used for install python, the second used for deply the code.

---

- name: Flask demo without using roles
  hosts: all                     

  tasks:
    - include_role:
        name: install-python
    - include_role:
        name: deploy-code
    - name: Start flask app
      shell: nohup ~/flask-ansible-demo/.env/bin/python ~/flask-ansible-demo/wsgi.py&
      register: weboutput
    
    - name: print the result
      debug:
        var: weboutput